name: "TagBot"

on:
  workflow_call:
    inputs:
      subdirs:
        description: "JSON array of subdir package names, e.g. '[\"NDTensors\"]'"
        required: false
        default: "[]"
        type: "string"
    secrets:
      TAGBOT_PAT:
        required: false

jobs:
  tagbot-itensor-registry:
    name: "TagBot (ITensorRegistry)"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - uses: "JuliaRegistries/TagBot@v1"
        with:
          token: "${{ secrets.TAGBOT_PAT || github.token }}"
          registry: "ITensor/ITensorRegistry"
  tagbot-general:
    name: "TagBot (General)"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - uses: "JuliaRegistries/TagBot@v1"
        with:
          token: "${{ secrets.TAGBOT_PAT || github.token }}"
  tagbot-general-subdirs:
    name: "TagBot (General Subdirs)"
    if: "${{ inputs.subdirs != '[]' }}"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    strategy:
      fail-fast: false
      matrix:
        subdir: "${{ fromJSON(inputs.subdirs) }}"
    steps:
      - uses: "ITensor/ITensorActions/.github/actions/tag-subdir@da93b046addb1a99cb6ab9461e79d35db51bb8a2"
        with:
          subdir: "${{ matrix.subdir }}"
          token: "${{ secrets.TAGBOT_PAT || github.token }}"
